[package]
name = "escher"
version = "0.0.0"
entrypoint = "src/lib.typ"
authors = ["Noah Syrkis <https://syrkis.com>"]
license = "MIT-0"
description = "A touying based slide tempalte."

[template]
path = "src/template"
entrypoint = "main.typ"
